### ISSUE TITLE
GromacsWrapper ≥ 0.7 supports Python 3.4+

### ISSUE THREAD

**Issue by orbeckst** [theavey/ParaTemp#35]
I am glad you find MDAnalysis and GromacsWrapper useful. I just wanted to point out that with the recent GW 0.7.0 release, Python 3 is also supported;
https://github.com/theavey/ParaTemp/blob/55001794e8d0abe97a34df92d3c7d8de983b2e6c/paratemp/__init__.py#L40

(If something is not working as expected, please raise an issue https://github.com/Becksteinlab/GromacsWrapper/issues – thanks!)

**Comment by theavey** [comment]
That’s great to hear! I’ll update shortly.

Thank you very much

**Comment by orbeckst** [comment]
👍

**Comment by orbeckst** [comment]
@theavey sorry to ask in a comment here but do you happen to have a paper/citation for ParaTemp – we are currently looking for projects that use GW https://github.com/Becksteinlab/GromacsWrapper/issues/163 ? Thanks!

**Comment by theavey** [comment]
No worries. 
I have not published it by itself yet. We submitted [a paper](https://chemrxiv.org/articles/Asymmetric_Synthesis_of_Griffipavixanthone_Employing_a_Chiral_Phosphoric_Acid-Catalyzed_Cycloaddition/7373969) about a week ago that mentions it, and I have plans to write up an individual paper for ParaTemp once I can clean it up some more.
